### ISSUE TITLE
Forecast starting point and times

### ISSUE THREAD

**Issue by Jack-H-Buckner** [Jack-H-Buckner/UniversalDiffEq.jl#14]
Double-check that the initial conditions and times where a forecast is evaluated match the initial points and times in the data they are compared to. Currently, the forecast function assumes the initial conditions occur at the first time point in the times vector.

**Comment by jarroyoe** [comment]
Jack, what exactly do you mean with this issue? The method `forecast(UDE,u0,t0,times)` seems to be working based on the tests.
