### ISSUE TITLE
Add MCMC algorithm to optimizers

### ISSUE THREAD

**Issue by Jack-H-Buckner** [Jack-H-Buckner/UniversalDiffEq.jl#27]
I want to see if it is possible to unify uncertinaty by using an MCMC sampler on the loss function.

**Comment by jarroyoe** [comment]
Added NUTS sampler on commit https://github.com/Jack-H-Buckner/UniversalDiffEq.jl/commit/9724962be922fe5718d65991e88d5b0f1a91e512. Will add SGLD soon.

NUTS sampler creates a vector of parameter draws. This is important to incorporate in other functions that might use a Bayesian parameterization of the model.

**Comment by jarroyoe** [comment]
Added SGLD on commit https://github.com/Jack-H-Buckner/UniversalDiffEq.jl/commit/4b6029f1f1b3d7c62010c5d7b74aa8a5628edb40.
