### ISSUE TITLE
Expand model analysis functions for multiple time series

### ISSUE THREAD

**Issue by zechmeunier** [Jack-H-Buckner/UniversalDiffEq.jl#31]
Currently, the functions `get_right_hand_side`, `phase_plane`, `print_parameter_estimates`, `plot_forecast`, `get_NN_parameters`, and `get_parameters` don't work for multiple time series. When I pass them models with the MultiUDE format, I get the error `MethodError: no method matching <function name>(::UniversalDiffEq.MultiUDE)`.

**Comment by jarroyoe** [comment]
`get_right_hand_side`, `print_parameter_estimates`, ` get_NN_parameters`, and `get_parameters` are all the same functioning and can be expanded to include `MultiUDE` on the same definition.

For `phase_plane`, the phase plane is mathematically the same, but we could be observing different regions with different time series. I think that `MultiUDE` would need to consider the boundaries of the phase plane based on the boundaries of the observed data.

I think that for `plot_forecast`, one would need to include an `id` to ensure the forecast takes a single time series.
Thoughts?

**Comment by jarroyoe** [comment]
Fixed the trivial cases on commit https://github.com/Jack-H-Buckner/UniversalDiffEq.jl/commit/881cdfefad0a1d172564817d88d38a6592085731

**Comment by 19fitzna** [comment]
> For `phase_plane`, the phase plane is mathematically the same, but we could be observing different regions with different time series. I think that `MultiUDE` would need to consider the boundaries of the phase plane based on the boundaries of the observed data.

Another issue is that `phase_plane` is hard-coded so that it only works for models with 2 state variables

**Comment by jarroyoe** [comment]
> > For `phase_plane`, the phase plane is mathematically the same, but we could be observing different regions with different time series. I think that `MultiUDE` would need to consider the boundaries of the phase plane based on the boundaries of the observed data.
> 
> Another issue is that `phase_plane` is hard-coded so that it only works for models with 2 state variables

Fixed in https://github.com/Jack-H-Buckner/UniversalDiffEq.jl/commit/22a2f67c2aae8b8c8186a758d29ac16bf153629d.

**Comment by 19fitzna** [comment]
I modified `phase_plane(UDE::MultiUDE)` in 4fc55e0 to plot a phase plane for each series in the data. The function previously didn't work as the call to `forecast()` within the function wasn't being given its required series argument. I don't know if this is appropriate or not, just a quick solution to get it working and probably warrants a change

**Comment by 19fitzna** [comment]
All functions mentioned appear to work for multiple time series as of a3c8e4b
