### ISSUE TITLE
Issues with DifferentialEquations and CUDA

### ISSUE THREAD

**Issue by 19fitzna** [Jack-H-Buckner/UniversalDiffEq.jl#33]
DifferentialEquations.jl has compatibility issues with several package versions, and as a result requires an out of date version of CUDA.jl which breaks the CUDA backend. So far we have only used the ordinary differential equation functionality from DifferentialEquations which are included in OrdinaryDiffEq.jl. Further, OrdinaryDiffEq does not have the same compatability issues as DifferentialEquations and works nicely with the newest version of CUDA.jl. If we want the GPU backend to work we should probably switch out DifferentialEquations for OrdinaryDiffEq

**Comment by jarroyoe** [comment]
This can be done just by replacing `using DifferentialEquations` with `using OrdinaryDiffEq` on `UniversalDiffEq.jl`. This is probably fine to do for now. Thinking on the end user, if you need stochastic solvers beyond Bayesian inference, it'll probably make more sense to stick to the `DiffEqFlux.jl` package.
