### ISSUE TITLE
Component Arrays Causing Scalar Indexing (GPU Backend)

### ISSUE THREAD

**Issue by 19fitzna** [Jack-H-Buckner/UniversalDiffEq.jl#39]
The use of ComponentArrays for the parameters of UDEs causes scalar indexing when moved to the graphics card. This results in training which is slower on the GPU than the CPU.

**Comment by jarroyoe** [comment]
If you search [on the DiffEqFlux issues](https://github.com/SciML/DiffEqFlux.jl/issues?q=unknown+parameters+UDE), you'll see this seems to be the way it's set up to be done. I have had a similar experience in the past trying to run UDEs on GPUs, so I would raise an issue with them to see if there's any way this can be overcome.

**Comment by 19fitzna** [comment]
Issue was due to feeding cuArrays into component arrays. Should be fixed in next commit to `GPU Support` branch
