### ISSUE TITLE
Build light version with core functionality and fewer dependencies

### ISSUE THREAD

**Issue by Jack-H-Buckner** [Jack-H-Buckner/UniversalDiffEq.jl#52]
I have been having trouble with precompilation issues I want to see if this helps.

**Comment by jarroyoe** [comment]
I think @19fitzna has done a lot of work figuring out dependencies in the toml file. The main compiling issue I see is the documentation, which I'm not sure what the pathway is to solve.

**Comment by 19fitzna** [comment]
> I think @19fitzna has done a lot of work figuring out dependencies in the toml file. The main compiling issue I see is the documentation, which I'm not sure what the pathway is to solve.

The issue with the documentation is due to #48. We just need to add the docstrings in the code somewhere in the documentation.  I can do this, but it might be better if the people who wrote the functions provide the descriptions just to ensure accuracy.

**Comment by 19fitzna** [comment]
> I have been having trouble with precompilation issues I want to see if this helps.

I wonder if it would potentially be better to do the opposite? We strip this package down to its core and move the extra stuff to additional packages which act as plug-ins?

**Comment by jarroyoe** [comment]
> > I have been having trouble with precompilation issues I want to see if this helps.
> 
> I wonder if it would potentially be better to do the opposite? We strip this package down to its core and move the extra stuff to additional packages which act as plug-ins?

This could be an option. Bayesian UDEs could be a separate package, but I wonder if at this point that would be an issue of splitting the audience too much.

**Comment by Jack-H-Buckner** [comment]
I just made this branch because I was having some trouble getting the
package to precompile on my machine and wanted to see if a lighter version
would help (it didn't). I think we should move forward with all the current
features. I think they are useful and the pacakge only takes a minute or
two to precompile on my machine.

**Comment by zechmeunier** [comment]
The precompilation for UniversalDiffEq and all the other packages in my coral analysis workflow only takes a couple minutes on my computer as well.

**Comment by jarroyoe** [comment]
As a clarification note, it would be hard to reduce the precompilation of the package by a significant amount because most of its dependencies (Lux and Plots come to mind) already take a long time precompiling.
