### ISSUE TITLE
Package Exports Need Docstrings

### ISSUE THREAD

**Issue by 19fitzna** [Jack-H-Buckner/UniversalDiffEq.jl#70]
Here is a list of items exported by the package which do not currently have docstrings:

DiscreteUDE  
MultiUDE  
LotkaVolterra  
plot\_leave\_future\_out\_cv  
func  
LorenzLotkaVolterra  
plot\_covariates  
vectorfield2d  
nullclines2d  
vectorfield\_and\_nullclines  

edit: shortened list of functions which still need docstrings

**Comment by 19fitzna** [comment]
> Just to make sure, they have to show up on a file in the `docs` within a @docs block?

To clarify, per our meeting yesterday, if we want all exported items from the package to have docstring descriptions, these items need both docstrings within the code and then also references within an @docs block.

**Comment by jarroyoe** [comment]
The docstrings of the functions in `Optimizers.jl` were commented so they were not being read. I took the comment hash out of them and other functions in https://github.com/Jack-H-Buckner/UniversalDiffEq.jl/commit/af9b0673072a077469d6649b9011b1e37152d5df
