### ISSUE TITLE
plot_bifurcation_diagram() doesn't work with wide-formatted covariate data

### ISSUE THREAD

**Issue by 19fitzna** [Jack-H-Buckner/UniversalDiffEq.jl#88]
`plot_bifurcation_diagram` relies on `model.variable_column_name` having a value which is not `nothing`

For instances where a user is using wide-format covariate data they set `variable_column_name = nothing` resulting in the following error when trying to use `plot_bifurcation_diagram` with a model using wide-format covariate data:

```
MethodError: no method matching getindex(::DataFrame, ::Colon, ::Nothing)

Stacktrace:
 [1] plot_bifrucation_diagram(model::MultiUDE, xvariable::String; N::Int64, color_variable::Nothing, conditional_variable::Nothing, size::Tuple{Int64, Int64})
   @ UniversalDiffEq C:\Users\user\.julia\packages\UniversalDiffEq\iRceU\src\ODEAnalysis.jl:678
 [2] plot_bifrucation_diagram(model::MultiUDE, xvariable::String)
   @ UniversalDiffEq C:\Users\user\.julia\packages\UniversalDiffEq\iRceU\src\ODEAnalysis.jl:657
```

I can include an MWE if needed but this should occur anytime when using `plot_bifurcation_diagram` for a model with kwarg `variable_column_name = nothing`

**Comment by zechmeunier** [comment]
Isn't it the behavior of most functions that take covariates to require them to be supplied in long format?

**Comment by 19fitzna** [comment]
At least within our package, all other functions that use covariates support both at this moment. 

As an alternative to changing this function to work with wide format we could drop wide-format support or provide a warning that wide format has limited functionality when defining a model with wide-format covariates.

**Comment by Jack-H-Buckner** [comment]
Thanks for catching this! I'll work on it - were you using a multiple or single time series model?

**Comment by 19fitzna** [comment]
I was using multiple time series
